### ISSUE TITLE
Add reference documentation for including JS modules (marked alpha)

### ISSUE THREAD

**Issue by mneise** [clojure/clojurescript-site#26]
The main source on how to include JavaScript modules is still my [blog](http://mneise.github.io/). It would be good to consolidate the information from the different blog posts and add documentation for JS module support to the site.

**Comment by mneise** [comment]
Started to work on this today, it's still work in progress though 😉  https://github.com/mneise/clojurescript-site/blob/master/content/reference/javascript-module-support.adoc.

**Comment by puredanger** [comment]
yay! would be great to include this, happy to merge when you think it's ready.

**Comment by jrheard** [comment]
Hi Maria! This functionality looks great, I'm excited to use it. I'm a complete rookie, so I figured I'd leave some feedback in case it's helpful: I used your linked documentation and http://mneise.github.io/posts/2015-06-15-week-3.html to use this `:module-type :commonjs` feature in my project, but I had a little trouble getting it working because I was confused about something. (please correct me if I'm wrong about any of this!)

It seems that doing this:

```
(ns foo.bar
  (:require [my-js-module]))

(my-js-module/baz)
```

will not work, and that instead it's necessary for me to do

```
(ns foo.bar
  (:require [my-js-module :as my-js-module])) ; have to include the explicit :as

(my-js-module/baz)
```

When I compile my cljs in verbose mode using the first of those two approaches, I see warning messages that look like this:

`WARNING: No such namespace: collision, could not locate collision.cljs, collision.cljc, or Closure namespace "" at line 66 /Users/jrheard/Dropbox/dev/voke/test/voke/system/collision_test.cljs`

where the `or Closure namespace ""` is probably the interesting bit.

Anyway, if this is known and intentional, I recommend calling it out more clearly in the documentation (unless it's already clearly spelled out in there and I just missed it). Thanks again!

**Comment by mneise** [comment]
@jrheard Thank you for the detailed issue description 👍  This behaviour is not intentional and I would consider it to be a bug. I created an [issue](http://dev.clojure.org/jira/browse/CLJS-1820) for this 😉 

@puredanger Created a PR. Should be good to go 😉

**Comment by puredanger** [comment]
Should be live now
